# Figure 2: PCA
DATASETS = ["bugeon", "bakken", "tosches", "tasic", "colquitt"]
# TODO: save e.g. gene lists to scratchpath 

rule intersect_genes:
    input:
        expand("results/pandas/genes_{dataset}.csv", 
        dataset=[dataset for dataset in DATASETS if dataset!="bugeon"]),
    output:
        shared_genes="results/pandas/shared_genes.txt",
    script:
        "fig2_intersect_genes.py"


rule datasets_table:
    input:
        expand("results/pandas/overview_{dataset}.csv", dataset=DATASETS),
    output:
        table="results/pandas/overview.csv",
        latex="results/pandas/overview.tex",
    script:
        "fig2_dataset_table.py"


rule datasets:
    input:
        anndata="data/anndata/{dataset}.h5ad",
    output:
        figure="figures/figure2/QC_{dataset}.png",
        table="results/pandas/overview_{dataset}.csv",
        genes="results/pandas/genes_{dataset}.csv",
    params:
        dataset=lambda wildcards: wildcards.dataset,
    script:
        "fig2_dataset_stats.py"
