## Constants for preprocessing
NORMALIZE_TARGET_SUM = 1e4
NUM_HVG_GENES = 2000
NUM_PCS = 30

# Circuit parameters
PV_MOUSE_MOD = -2
SST_MOUSE_MOD = 6
VIP_MOUSE_MOD = 8
PV_HUMAN_MOD = 0
SST_HUMAN_MOD = SST_MOUSE_MOD
VIP_HUMAN_MOD = VIP_MOUSE_MOD
PV_TURTLE_MOD = 0
SST_TURTLE_MOD = -1
VIP_TURTLE_MOD = 4